# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-26 02:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default=False)),
                ('p1_wins', models.PositiveIntegerField()),
                ('p2_wins', models.PositiveIntegerField()),
                ('p1_losses', models.PositiveIntegerField()),
                ('p2_losses', models.PositiveIntegerField()),
                ('p1_ties', models.PositiveIntegerField()),
                ('p2_ties', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DCI', models.BigIntegerField(unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('player_ids', models.CharField(max_length=5000)),
                ('host_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TourneyTime.Player')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='player1_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p1_id', to='TourneyTime.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='player2_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p2_id', to='TourneyTime.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='tournament_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TourneyTime.Tournament'),
        ),
    ]
